# Site Settings
title: Sudhakar Reddy Jerribanda
name: Sudhakar Reddy Jerribanda
description: Data Science Professional | Machine Learning | Database Management | AWS Certified
url: "https://sudhakarjerribanda.github.io/portfolio" # Updated GitHub Pages URL
baseurl: "" # Leave this empty if hosting at the root of your domain
repository: sudhakarjerribanda/portfolio # Updated GitHub repository
email: srippc@umsystem.edu
twitter_username: "" # Add if you have one
linkedin_username: "sudhakar-reddy-jerribanda-1845381b4" # Updated LinkedIn username
github_username: sudhakarjerribanda # Updated GitHub username

# Theme Settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default" # Options: default, dark, neon, mint, plum, sunrise

# Navigation
navigation:
  - text: "Home"
    url: /
  - text: "About Me"
    url: /about/
  - text: "Projects"
    url: /projects/
  - text: "Experience"
    url: /experience/
  - text: "Certifications"
    url: /certifications/
  - text: "Contact"
    url: /contact/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
      share: true
      comments: false
      read_time: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO Settings
seo:
  type: "Person" # For personal websites
  name: "Sudhakar Reddy Jerribanda"
  description: "Data Science Professional | Machine Learning | Database Management | AWS Certified"
  links:
    - "https://linkedin.com/in/sudhakar-reddy-jerribanda-1845381b4" # Updated LinkedIn URL
    - "https://github.com/sudhakarjerribanda/portfolio" # Updated GitHub URL

# Analytics (Optional)
#google_analytics: "UA-XXXXX-X" # Replace with your Google Analytics ID

# Social Sharing (Optional)
social:
  - name: "LinkedIn"
    icon: "fab fa-linkedin"
    url: "https://linkedin.com/in/sudhakar-reddy-jerribanda-1845381b4" # Updated LinkedIn URL
  - name: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/sudhakarjerribanda/portfolio" # Updated GitHub URL
  - name: "Email"
    icon: "fas fa-envelope"
    url: "mailto:srippc@umsystem.edu"

# Footer
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/sudhakar-reddy-jerribanda-1845381b4" # Updated LinkedIn URL
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/sudhakarjerribanda/portfolio" # Updated GitHub URL
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:srippc@umsystem.edu"
